# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_view.ui'
#
# Created: Sun Feb  3 20:06:29 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 775)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedPages = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedPages.setLineWidth(0)
        self.stackedPages.setObjectName("stackedPages")
        self.overview = QtWidgets.QWidget()
        self.overview.setObjectName("overview")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.overview)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolbarOverview = QtWidgets.QFrame(self.overview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarOverview.sizePolicy().hasHeightForWidth())
        self.toolbarOverview.setSizePolicy(sizePolicy)
        self.toolbarOverview.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarOverview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbarOverview.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbarOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbarOverview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbarOverview.setLineWidth(0)
        self.toolbarOverview.setObjectName("toolbarOverview")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbarOverview)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(250, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolScenarios = ToolButton(self.toolbarOverview)
        self.toolScenarios.setEnabled(False)
        self.toolScenarios.setMinimumSize(QtCore.QSize(50, 50))
        self.toolScenarios.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolScenarios.setBaseSize(QtCore.QSize(50, 50))
        self.toolScenarios.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/scenarios_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/img/scenarios_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolScenarios.setIcon(icon)
        self.toolScenarios.setIconSize(QtCore.QSize(30, 30))
        self.toolScenarios.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolScenarios.setObjectName("toolScenarios")
        self.horizontalLayout.addWidget(self.toolScenarios)
        self.selectorScenarios = QtWidgets.QComboBox(self.toolbarOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectorScenarios.sizePolicy().hasHeightForWidth())
        self.selectorScenarios.setSizePolicy(sizePolicy)
        self.selectorScenarios.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        self.selectorScenarios.setFont(font)
        self.selectorScenarios.setEditable(False)
        self.selectorScenarios.setMaxVisibleItems(5)
        self.selectorScenarios.setMaxCount(10)
        self.selectorScenarios.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.selectorScenarios.setIconSize(QtCore.QSize(0, 0))
        self.selectorScenarios.setFrame(True)
        self.selectorScenarios.setObjectName("selectorScenarios")
        self.selectorScenarios.addItem("")
        self.selectorScenarios.addItem("")
        self.horizontalLayout.addWidget(self.selectorScenarios)
        self.toolRun = ToolButton(self.toolbarOverview)
        self.toolRun.setEnabled(False)
        self.toolRun.setMinimumSize(QtCore.QSize(50, 50))
        self.toolRun.setBaseSize(QtCore.QSize(50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/run_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/run_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolRun.setIcon(icon1)
        self.toolRun.setIconSize(QtCore.QSize(30, 30))
        self.toolRun.setObjectName("toolRun")
        self.horizontalLayout.addWidget(self.toolRun)
        self.toolExport = ToolButton(self.toolbarOverview)
        self.toolExport.setEnabled(False)
        self.toolExport.setMinimumSize(QtCore.QSize(50, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/export_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/export_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolExport.setIcon(icon2)
        self.toolExport.setIconSize(QtCore.QSize(30, 30))
        self.toolExport.setObjectName("toolExport")
        self.horizontalLayout.addWidget(self.toolExport)
        spacerItem1 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.titleOverview = QtWidgets.QLabel(self.toolbarOverview)
        self.titleOverview.setMinimumSize(QtCore.QSize(0, 50))
        self.titleOverview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setWeight(50)
        font.setBold(False)
        self.titleOverview.setFont(font)
        self.titleOverview.setLineWidth(0)
        self.titleOverview.setAlignment(QtCore.Qt.AlignCenter)
        self.titleOverview.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleOverview.setObjectName("titleOverview")
        self.horizontalLayout.addWidget(self.titleOverview)
        spacerItem2 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(550, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.toolSidebarOverview = ToolButton(self.toolbarOverview)
        self.toolSidebarOverview.setEnabled(False)
        self.toolSidebarOverview.setMinimumSize(QtCore.QSize(50, 50))
        self.toolSidebarOverview.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/img/sidebar_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolSidebarOverview.setIcon(icon3)
        self.toolSidebarOverview.setIconSize(QtCore.QSize(30, 30))
        self.toolSidebarOverview.setCheckable(True)
        self.toolSidebarOverview.setChecked(True)
        self.toolSidebarOverview.setObjectName("toolSidebarOverview")
        self.horizontalLayout.addWidget(self.toolSidebarOverview)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(7, 1)
        self.verticalLayout.addWidget(self.toolbarOverview)
        self.mainOverview = QtWidgets.QFrame(self.overview)
        self.mainOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainOverview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainOverview.setLineWidth(0)
        self.mainOverview.setObjectName("mainOverview")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainOverview)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoFrame = QtWidgets.QFrame(self.mainOverview)
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setLineWidth(0)
        self.logoFrame.setObjectName("logoFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logoFrame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.layoutLogo = QtWidgets.QVBoxLayout()
        self.layoutLogo.setSpacing(0)
        self.layoutLogo.setObjectName("layoutLogo")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutLogo.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layoutLogo.addItem(spacerItem6)
        self.logo = SectionSelector(self.logoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(100, 100))
        self.logo.setMouseTracking(True)
        self.logo.setLineWidth(0)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/img/logo_light@2x.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.layoutLogo.addWidget(self.logo)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layoutLogo.addItem(spacerItem7)
        self.horizontalLayout_3.addLayout(self.layoutLogo)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_2.addWidget(self.logoFrame)
        self.sidebarOverview = Sidebar(self.mainOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarOverview.sizePolicy().hasHeightForWidth())
        self.sidebarOverview.setSizePolicy(sizePolicy)
        self.sidebarOverview.setMinimumSize(QtCore.QSize(0, 0))
        self.sidebarOverview.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebarOverview.setBaseSize(QtCore.QSize(0, 0))
        self.sidebarOverview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sidebarOverview.setLineWidth(0)
        self.sidebarOverview.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.sidebarOverview.setObjectName("sidebarOverview")
        self.horizontalLayout_2.addWidget(self.sidebarOverview)
        self.verticalLayout.addWidget(self.mainOverview)
        self.stackedPages.addWidget(self.overview)
        self.sections = QtWidgets.QWidget()
        self.sections.setObjectName("sections")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sections)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolbarSections = QtWidgets.QFrame(self.sections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarSections.sizePolicy().hasHeightForWidth())
        self.toolbarSections.setSizePolicy(sizePolicy)
        self.toolbarSections.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarSections.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbarSections.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbarSections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbarSections.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbarSections.setLineWidth(0)
        self.toolbarSections.setObjectName("toolbarSections")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.toolbarSections)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolBackSections = ToolButton(self.toolbarSections)
        self.toolBackSections.setEnabled(False)
        self.toolBackSections.setMinimumSize(QtCore.QSize(50, 50))
        self.toolBackSections.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBackSections.setBaseSize(QtCore.QSize(0, 0))
        self.toolBackSections.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/back_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/img/back_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolBackSections.setIcon(icon4)
        self.toolBackSections.setIconSize(QtCore.QSize(30, 30))
        self.toolBackSections.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBackSections.setObjectName("toolBackSections")
        self.horizontalLayout_4.addWidget(self.toolBackSections)
        self.toolDraft = ToolButton(self.toolbarSections)
        self.toolDraft.setEnabled(False)
        self.toolDraft.setMinimumSize(QtCore.QSize(50, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/img/draft_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolDraft.setIcon(icon5)
        self.toolDraft.setIconSize(QtCore.QSize(30, 30))
        self.toolDraft.setCheckable(True)
        self.toolDraft.setObjectName("toolDraft")
        self.horizontalLayout_4.addWidget(self.toolDraft)
        spacerItem9 = QtWidgets.QSpacerItem(150, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.toolGraph = ToolButton(self.toolbarSections)
        self.toolGraph.setEnabled(False)
        self.toolGraph.setMinimumSize(QtCore.QSize(50, 50))
        self.toolGraph.setBaseSize(QtCore.QSize(0, 0))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/graph_select@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/img/graph_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.toolGraph.setIcon(icon6)
        self.toolGraph.setIconSize(QtCore.QSize(30, 30))
        self.toolGraph.setObjectName("toolGraph")
        self.horizontalLayout_4.addWidget(self.toolGraph)
        spacerItem10 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.titleSections = QtWidgets.QLabel(self.toolbarSections)
        self.titleSections.setMinimumSize(QtCore.QSize(0, 50))
        self.titleSections.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.titleSections.setFont(font)
        self.titleSections.setLineWidth(0)
        self.titleSections.setAlignment(QtCore.Qt.AlignCenter)
        self.titleSections.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleSections.setObjectName("titleSections")
        self.horizontalLayout_4.addWidget(self.titleSections)
        spacerItem11 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(250, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.toolSidebarSections = ToolButton(self.toolbarSections)
        self.toolSidebarSections.setEnabled(False)
        self.toolSidebarSections.setMinimumSize(QtCore.QSize(50, 50))
        self.toolSidebarSections.setMaximumSize(QtCore.QSize(50, 50))
        self.toolSidebarSections.setIcon(icon3)
        self.toolSidebarSections.setIconSize(QtCore.QSize(30, 30))
        self.toolSidebarSections.setCheckable(True)
        self.toolSidebarSections.setObjectName("toolSidebarSections")
        self.horizontalLayout_4.addWidget(self.toolSidebarSections)
        self.verticalLayout_2.addWidget(self.toolbarSections)
        self.mainSections = QtWidgets.QHBoxLayout()
        self.mainSections.setSpacing(0)
        self.mainSections.setObjectName("mainSections")
        self.sectionView = QtWidgets.QGraphicsView(self.sections)
        self.sectionView.setObjectName("sectionView")
        self.mainSections.addWidget(self.sectionView)
        self.sidebarSections = Sidebar(self.sections)
        self.sidebarSections.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebarSections.setBaseSize(QtCore.QSize(260, 0))
        self.sidebarSections.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sidebarSections.setLineWidth(0)
        self.sidebarSections.setObjectName("sidebarSections")
        self.mainSections.addWidget(self.sidebarSections)
        self.verticalLayout_2.addLayout(self.mainSections)
        self.verticalLayout_2.setStretch(1, 1)
        self.stackedPages.addWidget(self.sections)
        self.draft = QtWidgets.QWidget()
        self.draft.setObjectName("draft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.draft)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolbarDraft = QtWidgets.QFrame(self.draft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarDraft.sizePolicy().hasHeightForWidth())
        self.toolbarDraft.setSizePolicy(sizePolicy)
        self.toolbarDraft.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarDraft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbarDraft.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbarDraft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbarDraft.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbarDraft.setLineWidth(0)
        self.toolbarDraft.setObjectName("toolbarDraft")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.toolbarDraft)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem13 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.toolBackDraft = ToolButton(self.toolbarDraft)
        self.toolBackDraft.setEnabled(False)
        self.toolBackDraft.setMinimumSize(QtCore.QSize(50, 50))
        self.toolBackDraft.setIcon(icon5)
        self.toolBackDraft.setIconSize(QtCore.QSize(30, 30))
        self.toolBackDraft.setCheckable(True)
        self.toolBackDraft.setChecked(True)
        self.toolBackDraft.setObjectName("toolBackDraft")
        self.horizontalLayout_5.addWidget(self.toolBackDraft)
        spacerItem14 = QtWidgets.QSpacerItem(150, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.toolCursor = ToolButton(self.toolbarDraft)
        self.toolCursor.setEnabled(False)
        self.toolCursor.setMinimumSize(QtCore.QSize(50, 50))
        self.toolCursor.setBaseSize(QtCore.QSize(50, 50))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/img/cursor_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolCursor.setIcon(icon7)
        self.toolCursor.setIconSize(QtCore.QSize(30, 30))
        self.toolCursor.setCheckable(True)
        self.toolCursor.setChecked(True)
        self.toolCursor.setObjectName("toolCursor")
        self.horizontalLayout_5.addWidget(self.toolCursor)
        self.toolConnect = ToolButton(self.toolbarDraft)
        self.toolConnect.setEnabled(False)
        self.toolConnect.setMinimumSize(QtCore.QSize(50, 50))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/img/connect_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolConnect.setIcon(icon8)
        self.toolConnect.setIconSize(QtCore.QSize(30, 30))
        self.toolConnect.setCheckable(True)
        self.toolConnect.setObjectName("toolConnect")
        self.horizontalLayout_5.addWidget(self.toolConnect)
        spacerItem15 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.titleDraft = QtWidgets.QLabel(self.toolbarDraft)
        self.titleDraft.setMinimumSize(QtCore.QSize(0, 50))
        self.titleDraft.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.titleDraft.setFont(font)
        self.titleDraft.setLineWidth(0)
        self.titleDraft.setAlignment(QtCore.Qt.AlignCenter)
        self.titleDraft.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleDraft.setObjectName("titleDraft")
        self.horizontalLayout_5.addWidget(self.titleDraft)
        spacerItem16 = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(300, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.toolSidebarDraft = ToolButton(self.toolbarDraft)
        self.toolSidebarDraft.setEnabled(False)
        self.toolSidebarDraft.setMinimumSize(QtCore.QSize(50, 50))
        self.toolSidebarDraft.setMaximumSize(QtCore.QSize(50, 50))
        self.toolSidebarDraft.setIcon(icon3)
        self.toolSidebarDraft.setIconSize(QtCore.QSize(30, 30))
        self.toolSidebarDraft.setObjectName("toolSidebarDraft")
        self.horizontalLayout_5.addWidget(self.toolSidebarDraft)
        self.verticalLayout_4.addWidget(self.toolbarDraft)
        self.mainDraft = QtWidgets.QHBoxLayout()
        self.mainDraft.setSpacing(0)
        self.mainDraft.setObjectName("mainDraft")
        self.draftbar = Sidebar(self.draft)
        self.draftbar.setMaximumSize(QtCore.QSize(260, 16777215))
        self.draftbar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.draftbar.setLineWidth(0)
        self.draftbar.setObjectName("draftbar")
        self.mainDraft.addWidget(self.draftbar)
        self.draftView = QtWidgets.QGraphicsView(self.draft)
        self.draftView.setObjectName("draftView")
        self.mainDraft.addWidget(self.draftView)
        self.sidebarDraft = Sidebar(self.draft)
        self.sidebarDraft.setMaximumSize(QtCore.QSize(260, 16777215))
        self.sidebarDraft.setBaseSize(QtCore.QSize(260, 0))
        self.sidebarDraft.setObjectName("sidebarDraft")
        self.mainDraft.addWidget(self.sidebarDraft)
        self.verticalLayout_4.addLayout(self.mainDraft)
        self.verticalLayout_4.setStretch(1, 1)
        self.stackedPages.addWidget(self.draft)
        self.graph = QtWidgets.QWidget()
        self.graph.setObjectName("graph")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graph)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.toolbarGraph = QtWidgets.QFrame(self.graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbarGraph.sizePolicy().hasHeightForWidth())
        self.toolbarGraph.setSizePolicy(sizePolicy)
        self.toolbarGraph.setMinimumSize(QtCore.QSize(0, 0))
        self.toolbarGraph.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolbarGraph.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolbarGraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbarGraph.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolbarGraph.setLineWidth(0)
        self.toolbarGraph.setObjectName("toolbarGraph")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.toolbarGraph)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.toolBackGraph = ToolButton(self.toolbarGraph)
        self.toolBackGraph.setEnabled(False)
        self.toolBackGraph.setMinimumSize(QtCore.QSize(50, 50))
        self.toolBackGraph.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBackGraph.setBaseSize(QtCore.QSize(50, 50))
        self.toolBackGraph.setText("")
        self.toolBackGraph.setIcon(icon4)
        self.toolBackGraph.setIconSize(QtCore.QSize(30, 30))
        self.toolBackGraph.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBackGraph.setObjectName("toolBackGraph")
        self.horizontalLayout_6.addWidget(self.toolBackGraph)
        spacerItem18 = QtWidgets.QSpacerItem(200, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.selectGraph = QtWidgets.QComboBox(self.toolbarGraph)
        self.selectGraph.setMinimumSize(QtCore.QSize(200, 30))
        self.selectGraph.setObjectName("selectGraph")
        self.horizontalLayout_6.addWidget(self.selectGraph)
        self.toolExportGraph = ToolButton(self.toolbarGraph)
        self.toolExportGraph.setEnabled(False)
        self.toolExportGraph.setMinimumSize(QtCore.QSize(50, 50))
        self.toolExportGraph.setBaseSize(QtCore.QSize(50, 50))
        self.toolExportGraph.setIcon(icon2)
        self.toolExportGraph.setIconSize(QtCore.QSize(30, 30))
        self.toolExportGraph.setObjectName("toolExportGraph")
        self.horizontalLayout_6.addWidget(self.toolExportGraph)
        spacerItem19 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.titleGraph = QtWidgets.QLabel(self.toolbarGraph)
        self.titleGraph.setMinimumSize(QtCore.QSize(0, 0))
        self.titleGraph.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.titleGraph.setFont(font)
        self.titleGraph.setLineWidth(0)
        self.titleGraph.setAlignment(QtCore.Qt.AlignCenter)
        self.titleGraph.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.titleGraph.setObjectName("titleGraph")
        self.horizontalLayout_6.addWidget(self.titleGraph)
        spacerItem20 = QtWidgets.QSpacerItem(0, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.toolCursorGraph = ToolButton(self.toolbarGraph)
        self.toolCursorGraph.setEnabled(False)
        self.toolCursorGraph.setMinimumSize(QtCore.QSize(50, 50))
        self.toolCursorGraph.setIcon(icon7)
        self.toolCursorGraph.setIconSize(QtCore.QSize(30, 30))
        self.toolCursorGraph.setCheckable(True)
        self.toolCursorGraph.setChecked(True)
        self.toolCursorGraph.setObjectName("toolCursorGraph")
        self.horizontalLayout_6.addWidget(self.toolCursorGraph)
        self.toolZoomIn = ToolButton(self.toolbarGraph)
        self.toolZoomIn.setEnabled(False)
        self.toolZoomIn.setMinimumSize(QtCore.QSize(50, 50))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(":/icons/img/zoom-in_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolZoomIn.setIcon(icon9)
        self.toolZoomIn.setIconSize(QtCore.QSize(30, 30))
        self.toolZoomIn.setCheckable(True)
        self.toolZoomIn.setObjectName("toolZoomIn")
        self.horizontalLayout_6.addWidget(self.toolZoomIn)
        self.toolZoomOut = ToolButton(self.toolbarGraph)
        self.toolZoomOut.setEnabled(False)
        self.toolZoomOut.setMinimumSize(QtCore.QSize(50, 50))
        self.toolZoomOut.setMaximumSize(QtCore.QSize(50, 50))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/icons/img/zoom-out_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolZoomOut.setIcon(icon10)
        self.toolZoomOut.setIconSize(QtCore.QSize(30, 30))
        self.toolZoomOut.setCheckable(True)
        self.toolZoomOut.setObjectName("toolZoomOut")
        self.horizontalLayout_6.addWidget(self.toolZoomOut)
        self.toolButton = ToolButton(self.toolbarGraph)
        self.toolButton.setEnabled(False)
        self.toolButton.setMinimumSize(QtCore.QSize(50, 50))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_select_orange@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_normal@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/icons/img/zoom-range_select_orange@2x.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.toolButton.setIcon(icon11)
        self.toolButton.setIconSize(QtCore.QSize(30, 30))
        self.toolButton.setCheckable(True)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_6.addWidget(self.toolButton)
        spacerItem21 = QtWidgets.QSpacerItem(300, 50, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem21)
        self.horizontalLayout_6.setStretch(8, 1)
        self.horizontalLayout_6.setStretch(10, 1)
        self.verticalLayout_5.addWidget(self.toolbarGraph)
        self.mainGraph = QtWidgets.QHBoxLayout()
        self.mainGraph.setSpacing(0)
        self.mainGraph.setObjectName("mainGraph")
        self.graphView = QtWidgets.QGraphicsView(self.graph)
        self.graphView.setObjectName("graphView")
        self.mainGraph.addWidget(self.graphView)
        self.verticalLayout_5.addLayout(self.mainGraph)
        self.verticalLayout_5.setStretch(1, 1)
        self.stackedPages.addWidget(self.graph)
        self.verticalLayout_3.addWidget(self.stackedPages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedPages.setCurrentIndex(0)
        self.selectorScenarios.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.selectorScenarios.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "Base Scenario", None, -1))
        self.selectorScenarios.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Base Scenario", None, -1))
        self.selectorScenarios.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Renewable Only", None, -1))
        self.toolRun.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolExport.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.titleOverview.setText(QtWidgets.QApplication.translate("MainWindow", "Overview", None, -1))
        self.toolSidebarOverview.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolDraft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolGraph.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.titleSections.setText(QtWidgets.QApplication.translate("MainWindow", "Energy", None, -1))
        self.toolSidebarSections.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolBackDraft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolCursor.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolConnect.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.titleDraft.setText(QtWidgets.QApplication.translate("MainWindow", "Energy - Draft", None, -1))
        self.toolSidebarDraft.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolExportGraph.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.titleGraph.setText(QtWidgets.QApplication.translate("MainWindow", "Commodity", None, -1))
        self.toolCursorGraph.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolZoomIn.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolZoomOut.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))

from views.components.section_selector import SectionSelector
from views.components.sidebar import Sidebar
from views.components.tool_button import ToolButton
import osdria_app_rc
import osdria_app_rc
