# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeDialog.ui'
#
# Created: Sun Jan 27 16:27:13 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(450, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowOpacity(1.0)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.welcomeFrame = QtWidgets.QFrame(Dialog)
        self.welcomeFrame.setMouseTracking(False)
        self.welcomeFrame.setAutoFillBackground(False)
        self.welcomeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcomeFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.welcomeFrame.setLineWidth(0)
        self.welcomeFrame.setObjectName("welcomeFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.welcomeFrame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutClose = QtWidgets.QHBoxLayout()
        self.horizontalLayoutClose.setSpacing(0)
        self.horizontalLayoutClose.setContentsMargins(10, 5, -1, -1)
        self.horizontalLayoutClose.setObjectName("horizontalLayoutClose")
        self.buttonClose = ToolButton(self.welcomeFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClose.sizePolicy().hasHeightForWidth())
        self.buttonClose.setSizePolicy(sizePolicy)
        self.buttonClose.setMinimumSize(QtCore.QSize(11, 11))
        self.buttonClose.setMaximumSize(QtCore.QSize(11, 11))
        self.buttonClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close_normal@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/close_select@2x.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.buttonClose.setIcon(icon)
        self.buttonClose.setIconSize(QtCore.QSize(11, 11))
        self.buttonClose.setCheckable(False)
        self.buttonClose.setChecked(False)
        self.buttonClose.setObjectName("buttonClose")
        self.horizontalLayoutClose.addWidget(self.buttonClose)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutClose.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayoutClose)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayoutContent = QtWidgets.QHBoxLayout()
        self.horizontalLayoutContent.setSpacing(0)
        self.horizontalLayoutContent.setObjectName("horizontalLayoutContent")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutContent.addItem(spacerItem2)
        self.verticalLayoutContent = QtWidgets.QVBoxLayout()
        self.verticalLayoutContent.setSpacing(5)
        self.verticalLayoutContent.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayoutContent.setObjectName("verticalLayoutContent")
        self.iconLogo = QtWidgets.QLabel(self.welcomeFrame)
        self.iconLogo.setText("")
        self.iconLogo.setPixmap(QtGui.QPixmap(":/icons/icons/logo@2x.png"))
        self.iconLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.iconLogo.setObjectName("iconLogo")
        self.verticalLayoutContent.addWidget(self.iconLogo)
        self.labelWelcome = QtWidgets.QLabel(self.welcomeFrame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayoutContent.addWidget(self.labelWelcome)
        self.frameCreate = ProjectButton(self.welcomeFrame)
        self.frameCreate.setCursor(QtCore.Qt.PointingHandCursor)
        self.frameCreate.setObjectName("frameCreate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frameCreate)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iconCreate = QtWidgets.QLabel(self.frameCreate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconCreate.sizePolicy().hasHeightForWidth())
        self.iconCreate.setSizePolicy(sizePolicy)
        self.iconCreate.setText("")
        self.iconCreate.setPixmap(QtGui.QPixmap(":/icons/icons/new@2x.png"))
        self.iconCreate.setAlignment(QtCore.Qt.AlignCenter)
        self.iconCreate.setObjectName("iconCreate")
        self.horizontalLayout_3.addWidget(self.iconCreate)
        self.textLayoutCreate = QtWidgets.QVBoxLayout()
        self.textLayoutCreate.setSpacing(0)
        self.textLayoutCreate.setObjectName("textLayoutCreate")
        self.labelCreateTitle = QtWidgets.QLabel(self.frameCreate)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.labelCreateTitle.setFont(font)
        self.labelCreateTitle.setObjectName("labelCreateTitle")
        self.textLayoutCreate.addWidget(self.labelCreateTitle)
        self.labelCreateSub = QtWidgets.QLabel(self.frameCreate)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelCreateSub.setFont(font)
        self.labelCreateSub.setObjectName("labelCreateSub")
        self.textLayoutCreate.addWidget(self.labelCreateSub)
        self.horizontalLayout_3.addLayout(self.textLayoutCreate)
        self.verticalLayoutContent.addWidget(self.frameCreate)
        self.frameOpen = ProjectButton(self.welcomeFrame)
        self.frameOpen.setMinimumSize(QtCore.QSize(0, 0))
        self.frameOpen.setCursor(QtCore.Qt.PointingHandCursor)
        self.frameOpen.setObjectName("frameOpen")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameOpen)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.iconOpen = QtWidgets.QLabel(self.frameOpen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iconOpen.sizePolicy().hasHeightForWidth())
        self.iconOpen.setSizePolicy(sizePolicy)
        self.iconOpen.setText("")
        self.iconOpen.setPixmap(QtGui.QPixmap(":/icons/icons/open@2x.png"))
        self.iconOpen.setAlignment(QtCore.Qt.AlignCenter)
        self.iconOpen.setObjectName("iconOpen")
        self.horizontalLayout_4.addWidget(self.iconOpen)
        self.textLayoutOpen = QtWidgets.QVBoxLayout()
        self.textLayoutOpen.setSpacing(0)
        self.textLayoutOpen.setObjectName("textLayoutOpen")
        self.labelOpenTitle = QtWidgets.QLabel(self.frameOpen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setWeight(75)
        font.setBold(True)
        self.labelOpenTitle.setFont(font)
        self.labelOpenTitle.setObjectName("labelOpenTitle")
        self.textLayoutOpen.addWidget(self.labelOpenTitle)
        self.labelOpenSub = QtWidgets.QLabel(self.frameOpen)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.labelOpenSub.setFont(font)
        self.labelOpenSub.setObjectName("labelOpenSub")
        self.textLayoutOpen.addWidget(self.labelOpenSub)
        self.horizontalLayout_4.addLayout(self.textLayoutOpen)
        self.verticalLayoutContent.addWidget(self.frameOpen)
        self.horizontalLayoutContent.addLayout(self.verticalLayoutContent)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutContent.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayoutContent)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addWidget(self.welcomeFrame, 0, 0, 1, 1)
        self.actionOpen = QtWidgets.QAction(Dialog)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(Dialog)
        self.actionNew.setObjectName("actionNew")
        self.actionClose = QtWidgets.QAction(Dialog)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL("triggered()"), Dialog.reject)
        QtCore.QObject.connect(self.buttonClose, QtCore.SIGNAL("clicked()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.labelWelcome.setText(QtWidgets.QApplication.translate("Dialog", "Welcome to OSDRIA", None, -1))
        self.labelCreateTitle.setText(QtWidgets.QApplication.translate("Dialog", "Create ...", None, -1))
        self.labelCreateSub.setText(QtWidgets.QApplication.translate("Dialog", "New OSDRIA project", None, -1))
        self.labelOpenTitle.setText(QtWidgets.QApplication.translate("Dialog", "Open ...", None, -1))
        self.labelOpenSub.setText(QtWidgets.QApplication.translate("Dialog", "Existing OSDRIA project", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("Dialog", "open", None, -1))
        self.actionOpen.setShortcut(QtWidgets.QApplication.translate("Dialog", "Ctrl+O", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("Dialog", "new", None, -1))
        self.actionNew.setShortcut(QtWidgets.QApplication.translate("Dialog", "Ctrl+N", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("Dialog", "close", None, -1))
        self.actionClose.setShortcut(QtWidgets.QApplication.translate("Dialog", "Ctrl+Q", None, -1))

from projectButton import ProjectButton
from toolButton import ToolButton
import icons_rc
